import { Inter } from "next/font/google";
import { Navbar } from "@/components/navbar";

import Dashboard from "@/components/dashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <div className={`${inter.className} bg-[#f3f3f1]`}>
      <Navbar />
      <Dashboard>{children}</Dashboard>
    </div>
  );
}
