import { Inter } from "next/font/google";

import Dashboard from "@/components/admin/dashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <div className={`bg-[#f3f3f1]`}>
      {/* <AdminNavbar /> */}
      <Dashboard>{children}</Dashboard>
    </div>
  );
}
