import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { Navbar } from "@/components/navbar";
import Providers from "@/utils/providers";
import { MainContextProvider } from "@/context/main-context";

import "./globals.css";
import Dashboard from "@/components/dashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Toaster />
      <body className={inter.className}>
        <Providers>
          <MainContextProvider>
            <Navbar />
            <Dashboard>{children}</Dashboard>
          </MainContextProvider>
        </Providers>
      </body>
    </html>
  );
}
