import { Inter } from "next/font/google";

import Dashboard from "@/components/admin/dashboard";
import HomeNavbar from "@/components/home/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Showcase sign up",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className={`${inter.className}`}>
      <HomeNavbar />
      <main>{children}</main>
    </div>
  );
}
